---
spring:
  config.activate.on-profile: default
cds:
  datasource:
    auto-config.enabled: false
  security:
    mock:
      users:
        - name: admin
          password: pass_admin
          roles:
            - Administrators

